### ISSUE TITLE
Cannot plot the density of states

### ISSUE THREAD

**Issue by Timtansiyu** [deepmodeling/abacus-develop#3926]
### Details

Cannot successfully plot the density of states
[21spinele0.13dos.zip](https://github.com/deepmodeling/abacus-develop/files/14896996/21spinele0.13dos.zip)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [X] Yes, I have read the FAQ part on online manual.

### Task list for Issue attackers (only for developers)

- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by Timtansiyu** [comment]
![屏幕截图 2024-04-07 200301](https://github.com/deepmodeling/abacus-develop/assets/164017480/9224f34f-a5ab-49e8-8010-96202ab96df3)

**Comment by Timtansiyu** [comment]
![image](https://github.com/deepmodeling/abacus-develop/assets/164017480/c5c40098-ec95-4c3f-8abb-3fdb23fa12bc)
![image](https://github.com/deepmodeling/abacus-develop/assets/164017480/759d14f8-c218-4078-9548-57b998a7a8db)
Did I compile abacus-plot successfully?

**Comment by 1041176461** [comment]
I have fixed this bug in PR(https://github.com/deepmodeling/abacus-develop/pull/3928). And you should use `config.json` as below:
```json
{
    "tdosfile": "TDOS",
    "efermi": [-3.21088, -3.21088],
    "energy_range": [-1,1],
    "dos_range": [-5,5],
    
    "tdosfig": "tdos.png"
}
```
then, TDOS can be obtained
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/b9d56062-8a69-445c-8e19-1b84ad2b8226)

**Comment by Timtansiyu** [comment]
I tried using the config.json file you gave me and still got the same error. I was able to plot the band with abacus-plot-b, but I still couldn't plot the density of states with abacus-plot-d

**Comment by Timtansiyu** [comment]
![image](https://github.com/deepmodeling/abacus-develop/assets/164017480/60cc5d07-e647-429f-beb9-03d59f2a076b)

**Comment by 1041176461** [comment]
You should update the dos.py in PR(https://github.com/deepmodeling/abacus-develop/pull/3928)

**Comment by Timtansiyu** [comment]
I still have the above problem after updating dos.py according to #3928. Here is my changed dos.py file
[dos.docx](https://github.com/deepmodeling/abacus-develop/files/14903131/dos.docx)

**Comment by 1041176461** [comment]
Please download the newest `plot-tools` from the develop branch and reinstall it using `python setup.py install`

**Comment by Timtansiyu** [comment]
![image](https://github.com/deepmodeling/abacus-develop/assets/164017480/5285d885-c979-4b25-b209-15a485e858fd)
Still having the same problem, what should I do?

**Comment by Timtansiyu** [comment]
Is it because python is not applicable?

**Comment by 1041176461** [comment]
This error is because the parameters in hstack are not bracketed. 
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/df137542-aeff-4d18-996c-594399a49832)
I fixed this bug and optimized the output images in the latest version.

From your figure, I think you still use the old version of plot-tools. I have two suggestions here：

1. Completely delete the old version, i.e. this file
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/880f6a54-33ce-440f-b310-b29f77d8ae26)
and then reinstall the newest version

2.  Change to a new environment, for example, another virtual environment or your own PC, and then reinstall the newest version.

**Comment by WHUweiqingzhou** [comment]
@Timtansiyu could we close this issue now?
